### ISSUE TITLE
The way to get the taintAnalysis_log

### ISSUE THREAD

**Issue by PegX** [hwsel/tzslicer#1]
Hi, I wanna clarify how can i get the taintAnalysis_log file. 

When i checked the script, I found these  lines and I suppose that the first parameter of function read_taintAnalysis_log() is the name of the taint Analysis.

taintAnalysis_log = sys.argv[1] + "/" + sys.argv[1] + ".txt"

However, since your framework is based on the taintgrind which is the binary based tool to do dynamic analysis. It means first of all we need the executable (binary) and then feed it into the taintgrind and get the taintAnalysis. 

I am not very sure how can i get the taintAnalysis.txt correctly?
I tried with [../taintgrind] ../inst/bin/valgrind --tool=taintgrind tests/sign32 from this link: https://github.com/wmkhoo/taintgrind
And it of course can print the taint propagation information. Should I just write the terminal output as taintAnalysis.txt?

**Comment by hwsel** [comment]
Thank you for your question. You can run the [bash script](https://github.com/hwsel/tzslicer/blob/master/TZSlicer/run.sh) to generate the taint analysis log as a .txt file and execute the TZSlicer tool.

**Comment by PegX** [comment]
Thanks for your suggestion.
Another problem I met is that using read_taintAnalysis_log() and determine_functions() I can only get the functions with "s" labels because read_taintAnalysis_log() reads log from .txt file which only has the tainted functions. However, for the normal function, I did not get where is the source to read the functions from source file?

**Comment by hwsel** [comment]
The normal function is generated based on the functions/lines with "s" labels in the source file. In the determine_functions(), all_functions[function_index].append('n') is to label the normal functions. In particular, in the TZL mode, TZSlicer first labels the sensitive lines as "s". Then, after analyzing the source file and the lines with "s" labels, it labels the remaining lines as "b", "n", or "x" ("b" indicates the line showing in both worlds. "n" indicates the line showing in the normal world only. "x" indicates the deleted line).

**Comment by PegX** [comment]
I checked determine_functions(), however, it cannot get the list of the
normal functions. You can try with the FFT program with another function in
fft.c.

JUST DO IT!

**Comment by hwsel** [comment]
If you run FFT with TZ-M mode, it is correct that you could not get the normal function list. In the TZ-M mode, all the functions of FFT are put into the secure world. However, if you run TZ-B and TZ-L modes, you should be able to see the normal function list. Hope it helps.

**Comment by PegX** [comment]
Great. Thanks. I suppose my problem is that I just test with TZ-M mode.

**Comment by hwsel** [comment]
You are welcome! Please feel free to let us know if you encounter any other problems.
